CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS exemplo (
    id SERIAL PRIMARY KEY,
    nome TEXT,
    valor INTEGER
);
INSERT INTO exemplo (nome, valor) VALUES ('teste', 1) ON CONFLICT DO NOTHING;

CREATE ROLE readonly LOGIN PASSWORD 'readonlypass';
GRANT CONNECT ON DATABASE appdb TO readonly;
GRANT USAGE ON SCHEMA public TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;
